---

- name: Check node Version
  shell: node -v
  ignore_errors: yes
  register: nodev

- name: add nodejs ppa
  apt_repository: repo='ppa:chris-lea/node.js'
  when: nodev | failed

- name: install nodejs
  apt: name=nodejs state=latest
  when: nodev | failed

- name: Check if symlinked properly
  stat: path=/usr/bin/node
  register: nodesym

- name: setup Ubuntu Symlink (debug-fix)
  shell: "ln -s /usr/bin/nodejs /usr/bin/node"
  when: nodesym.stat.islink is defined and nodesym.stat.islink == false
  sudo: yes
